### ISSUE TITLE
Test different gravity solvers to measure their consistency with Quijote

### ISSUE THREAD

**Issue by maho3** [maho3/ltu-gobig#15]
There currently exists some weirdness going on with the current BORG-LPT and pmwd implementations which result in biased power spectra, even at large scales.

![Image](https://github.com/maho3/ltu-gobig/assets/11132524/703bf3bc-f90b-48cd-9122-89f02675c628)

Also, pmwd's growth factor calculation seems off for unknown reasons (See @shivampcosmo 's tests). And, pmwd's necessity to run on GPU make it prohibitive to run for the 3Gpc/h simulations. So, it is worth doing an exhaustive comparison of the methods available to us.

Gravity solvers to check:

- [BORG-LPT and BORG-PM](https://www.aquila-consortium.org/docs/borg/main/user/building.html)
- [pmwd](https://github.com/eelregit/pmwd)
- [fastPM](https://github.com/fastpm/fastpm)
- [S-COLA](https://bitbucket.org/florent-leclercq/simbelmyne/src/main/)
- [PM++](https://github.com/rouzib/PMpp)

If the P(k)'s of all the above listed methods are biased, we might consider correcting the final density fields with an analytic transfer function such as [syren](https://arxiv.org/pdf/2402.17492.pdf)

**Definition of done**
- [ ] Plot 1-pt and 2-pt stats for all above gravity solvers at the same initial conditions as Quijote
- [ ] Plot the above stats, but for different cosmologies and hyperparameters (resolution, B, etc).
- [ ] If necessary, implement a transfer function correction in ltu-cmass

**Comment by lavaux** [comment]
As discussed at the meeting let's try to use the exact same solvers. I tried to have consistent CLASS transfer function by relying on borg_pmwd (https://bitbucket.org/aquila-consortium/borg_pmwd/src/main/), however I was reported some defects in the P(k) at PMWD side that I did not have time to investigate.

**Comment by maho3** [comment]
Contact people individually about running these ICs

- BORG - @DeaglanBartlett 
- pmwd - @modichirag
- fastPM - @shivampcosmo or his code
- S-COLA - ?
- PM++ - @rouzib

**Comment by maho3** [comment]
This could be caused by an offset difference within the interpolated density field as in https://github.com/maho3/ltu-cmass/issues/8

**Comment by maho3** [comment]
Offsetting the interpolated density field by half a voxel doesn't seem to help the Pk bias at all, largely since the Pk should be shift-invariant.

**Comment by maho3** [comment]
![Image](https://github.com/maho3/ltu-gobig/assets/11132524/fe838a64-1c98-423a-9aac-d6f8baafada0)



![Image](https://github.com/maho3/ltu-gobig/assets/11132524/a5ac82eb-8528-4ec0-8f94-132aa408e289)

**Comment by maho3** [comment]
Todo:
- [ ] Check Omega_m 
- [ ] Increase force resolution
- [ ] Run other simulators
- [ ] Truncate even more -> See if wiggles get worse
- [ ] Convolve+stride high resolution

**Comment by maho3** [comment]
Most of the experiments suggested previously seem to have little-to-no effect on removing the transfer function 'wiggles' at low-$k$.

The only things which seem to significantly affect the transfer function wiggles have seemed to be:
- Playing with the EH transfer function fit parameters in [pmwd's Configuration](https://github.com/eelregit/pmwd/blob/ca91e43c41fa1de217341ecbc1909647eedc53de/pmwd/configuration.py#L53)
- Reducing the z_start to ~10 instead of ~100

This leads me to the suspicion that the transfer function is broken in pmwd, or at least systematically biased. The next steps is definitely to try this with fastPM, PM++, and BORG-PM.

**Comment by DeaglanBartlett** [comment]
BORG-PM seems to not have this problem. Here is the field, power spectrum and cross-spectrum when running BORG with the Quijote initial conditions.
![BORG_field_0](https://github.com/maho3/ltu-gobig/assets/47668431/98108aa6-5a8d-4013-9ffc-2557c2c8f78b)
![BORG_power_spectrum_0](https://github.com/maho3/ltu-gobig/assets/47668431/2556c33c-9be3-403e-9762-2f882eee753e)
The only discrepancies happen at the point where the removal of the CIC kernel has a big impact, so I think we can be confident that this is working quite well.

I can therefore implement this model into the pipeline. Where would you like this? In the ltu-cmass directory or ltu-gobig?

**Comment by maho3** [comment]
Awesome! Great to hear. It's still worth us trying to figure out what caused this, but this should probably replace pmwd as our main gravity solver. I have a feeling its the CLASS BORG transfer function that's solving the wiggles.

You can make a copy of [`nbody/borglpt.py`](https://github.com/maho3/ltu-cmass/blob/main/cmass/nbody/borglpt.py) as a new file, `borgpm.py`. And then simply replace any bits of the forward model that you need to, as well as add any further configurations you may need

**Comment by modichirag** [comment]
> Most of the experiments suggested previously seem to have little-to-no effect on removing the transfer function 'wiggles' at low-$k$.
> 
> The only things which seem to significantly affect the transfer function wiggles have seemed to be:
> 
>     * Playing with the EH transfer function fit parameters in [pmwd's Configuration](https://github.com/eelregit/pmwd/blob/ca91e43c41fa1de217341ecbc1909647eedc53de/pmwd/configuration.py#L53)
> 
>     * Reducing the z_start to ~10 instead of ~100
> 

Hmm, this might be it? I forgot that to have gradients with respect to cosmology, pmwd uses analytic EH transfer functions which might not be exactly the same as the transfer functions from CLASS/CAMB. 
So maybe if we generate the correct ICs (with the transfer function) and then use pmwd to only evolve the particles, we might not have this issue? Unless you are already doing that. 

Also I thought you always want to start from z=10/20 for any PM sim instead of z=100 or so?

**Comment by DeaglanBartlett** [comment]
The hunch that the issue with the final transfer function is due to using the Eisenstein&Hu (EH) formula seems to be correct. Here I run both BORG-LPT (2nd order) and BORG-PM with the following setup
```
N = 128
Lbox = 1000
zi = 20
nsteps = 50
```
and use the cosmology and white noise matched to Quijote simulation 0. I then run BORG to redshift 0 and compare to the redshift 0 Quijote field. For each of the BORG models I generate the ICs from the white noise using either EH or CLASS. Here are the resulting fields, power spectra and cross-spectra.
![BORG_field_0 (1)](https://github.com/maho3/ltu-gobig/assets/47668431/832dd880-1d93-487c-b8b6-56e93925e6a0)
![gravity_model_power_spectra_0](https://github.com/maho3/ltu-gobig/assets/47668431/98dd12db-9f38-4282-9c0f-bfc1babdf627)

From the middle panel we see clearly that there are oscillations (as @maho3 originally reported) in the ratio of the power spectra when using the EH formula, but these disappear when using CLASS. It seems to be clear that we should not generate ICs with EH. 

For BORG we can just use CLASS as done here. If we wish to use the pmwd gravity model perhaps we can generate the ICs externally (since pmwd wants you to use EH). As @modichirag mentions, EH is used in pmwd since it is analytic so can be differentiated. Perhaps implementing the corrections presented in Eq. 6 of [Bartlett et al. 2023 ](https://arxiv.org/abs/2311.15865) could resolve this issue while remaining differentiable, as these reduce the errors on T(k) to sub-percent levels (Figure 4).

**Comment by maho3** [comment]
@shivampcosmo 's FastPM runs which use a CAMB transfer function also exhibit slight wiggles, although not as severe as those of the EH transfer function.

![image](https://github.com/maho3/ltu-gobig/assets/11132524/9ca43b58-b23c-4b1d-9c54-6e7ebfbe8443)

**Comment by maho3** [comment]
For the 'problematic' cosmology of LH:99, Deaglan's BORG-PM improvements greatly help the wiggles, but don't totally eliminate them



![Image](https://github.com/maho3/ltu-gobig/assets/11132524/db222440-b225-4a07-91dd-a1f9689ebb84)

**Comment by DeaglanBartlett** [comment]
As a note, the Quijote simulations are initialised using camb rather than class (https://arxiv.org/pdf/1909.05273.pdf Section 2, paragraph 2), but one would hope that any final inference results are insensitive to the choice between these codes. It is less important whether the result is insensitive to EH as this is known to be a much worse approximation to T(k) than camb or class.

**Comment by shivampcosmo** [comment]
Also, what I was remembering regarding increasing force resolution suppressing wiggles was actually for fastpm and not pmwd. here is one example when changing the force grid resolution from B=2 to B=3. 

<img width="579" alt="image" src="https://github.com/maho3/ltu-gobig/assets/32287865/ef48286b-f210-4576-9935-2db8006c28b2">

**Comment by ludvigdoeser** [comment]
I investigated the sensitivity to cosmology by plotting the transfer function for different cosmologies from the LH. The comparison between BORG-1LPT and Quijote is made at the full LH-resolution using 512^3 particles in 1000 Mpc/h. Note that the BORG-1LPT used CLASS(!) and Qujote (as @DeaglanBartlett pointed out recently) uses CAMB. As @maho3 posted above, the most 'problematic' LH seen so far in terms of the wiggles seems to be 99. For other cosmologies, they are not as prominent (e.g. for LH98 they are negligible). 

![LH0_1_96_97_98_99](https://github.com/maho3/ltu-gobig/assets/21685177/721a5028-c9e6-42ab-a4ef-c94abe80fec6)

In terms of CAMB vs CLASS, there is no indication of any major discrepancy, at least not for the fiducial cosmology:
![class_vs_camb](https://github.com/maho3/ltu-gobig/assets/21685177/ae8022b0-4059-408d-b25a-cf1fcce9e47e)

**Comment by maho3** [comment]
Closing this because we know the issue now.

I've created [ltu-cmass#17](https://github.com/maho3/ltu-cmass/issues/17) and [ltu-cmass#18](https://github.com/maho3/ltu-cmass/issues/18) to implement the other solvers (fastPM and PM++) in ltu-cmass.

**Comment by maho3** [comment]
FYI, I've now done some tests of borgpm vs pmwd at z=0.5.

![image](https://github.com/maho3/ltu-gobig/assets/11132524/ffafc3da-3ac7-405f-974b-0138e1e68c05)
![image](https://github.com/maho3/ltu-gobig/assets/11132524/343ac7e4-a82c-42fc-8489-2c55b9d7a877)

These trends^ seem pretty consistent across different cosmologies. They may be improved with FastPM.

`pmwd` seems to have an overall variance bias, which is probably caused by its miscalculation of the growth factor.

Tagging relevant people: @shivampcosmo @ludvigdoeser @DeaglanBartlett

**Comment by adrianbayer** [comment]
@shivampcosmo I was just chatting with @maho3 and was wondering if you know what's causing the 20% discrepancy for pmwd? I've never explicitly tested z !=0 but it's a bit surprising. I recall having some normalization issues with the power spectrum in the past which I fixed by normalizing by some function of the growth factor, so may be there is a fix. Do you have the script you used to make the line? I'd be happy to take a quick look!

**Comment by shivampcosmo** [comment]
Yes, I don't understand the behavior at z!=0 either. Probably I am using it wrong, but here is the [script](/mnt/ceph/users/cmodi/fastpm-shivam/WHITE_NOISE_LH_QUIJOTE/test_pmwd/test_pmwd_z0p5.py) and the ICs (in the same folder) to reproduce the behavior. I am presuming you have rusty access. If not, I have also put it here https://www.dropbox.com/scl/fo/vdmovarsdcoeax933vmu7/AHlKqgZ3cwbY6NaEirfqvI0?rlkey=lizwr8drwg4qn8bwau9rl7trh&dl=0 . The main growth function in pmwd is not normalized (so I think it is being normalized somewhere inside main nbody calculation). But the discrepancy in the power spectrum ratio is different from growth function normalization discrepancy. I have also explicitly corrected that in the source code and it does not change this behavior of power spectrum mismatch for z!=0. I have not looked inside the nbody function yet, but if you are already familiar with that, probably you already know how to fix this (or if script in here has a bug).

**Comment by adrianbayer** [comment]
Hmmm, I see. The initial condition files are at z=0?

**Comment by shivampcosmo** [comment]
The initial conditions files are just gaussian random field modes with phases (generated with NGenic: https://github.com/maho3/ltu-cmass/tree/main/quijote_wn). These are passed to the LPT module then to get the ICs at some initial redshift and which are then evolved to z=0.5.
